export enum OpenZWaveEventType {
  DRIVER_READY = 'driver_ready',
  DRIVER_FAILED = 'driver_failed',
  CONNECTED = 'connected',
  SCAN_COMPLETE = 'scan_complete',
  NODE_ADDED = 'node_added',
  NODE_REMOVED = 'node_removed',
  NODE_NAMING = 'node_naming',
  NODE_AVAILABLE = 'node_available',
  NODE_READY = 'node_ready',
  POLLING_ENABLED = 'polling_enabled',
  POLLING_DISABLED = 'polling_disabled',
  SCENE_EVENT = 'scene_event',
  VALUE_ADDED = 'value_added',
  VALUE_CHANGED = 'value_changed',
  VALUE_REFRESHED = 'value_refreshed',
  VALUE_REMOVED = 'value_removed',
  CONTROLLER_COMMAND = 'controller_command',
}
