export const NODES_NORMALIZED = 'NODES_NORMALIZED';
export const NODE_NORMALIZED = 'NODE_NORMALIZED';
export const ZONE_PROBABILITY = 'ZONE_PROBABILITY';

export const LOCK_TIMEOUT = 20 * 1000;
export const MOTION_TIMEOUT = 5 * 1000;
export const SWITCH_TO_INACTIVE_AFTER = 15 * 1000;
export const SWITCH_TO_INACTIVE_AFTER_TICK = 5 * 1000;
export const DEBUG = true;
